### ISSUE TITLE
Start counting time when the first letter is pressed instead of when the page is loaded.

### ISSUE THREAD

**Issue by mycielski** [0ql/Donkeytype#2]
Currently the timer starts counting down immediately upon loading the page. It would be a massive improvement if the time started the moment the player presses a letter key instead (just like monkeytype does it).

**Comment by 0ql** [comment]
Fixed in https://github.com/0ql/Donkeytype/commit/1fd811b30125ebd4a74779ed02d7a6fb93f4dbc9.
