### ISSUE TITLE
Letter color does not change when the letter is deleted

### ISSUE THREAD

**Issue by mycielski** [0ql/Donkeytype#3]
Pressing backspace key removes the letter and moves the caret back one character however it does not affect the color of the deleted character. I think it should go back to the color it was before being typed in the first place.

**Comment by 0ql** [comment]
Personally I think it's actually helpful to see what letters you messed up when retyping them.

**Comment by 0ql** [comment]
Fixed in https://github.com/0ql/Donkeytype/commit/6d91960a21fdd4b5c8ba02138c77423c37996290.
