### ISSUE TITLE
Key rebinding doesn't work properly

### ISSUE THREAD

**Issue by interfazer** [0ql/Donkeytype#5]
Trying to replicate Monkeytype's "quick tab" to swiftly restart the test by pressing just one key, I find that it's not possible to change the hotkeys by writing their name in the interface. Neither "shift" nor "Esc" have any effect on the behavior of the application.

The lack of an "Apply" or "Save" button also make the process confusing and as the user I have to check visually/by spamming the key I tried to rebind to confirm if my changes were applied.

**Comment by 0ql** [comment]
In https://github.com/0ql/Donkeytype/commit/da50de12c1886699747b81c205b52439214c52ac i added further information on what words to use:

To bind the Escape button type "Escape". Same with "Alt", "Tab" and "Control". You can also map the same key to the leader and for example "Reset Run" to double press the key to reset.

Hope this helps.
